[program:gunicorn]
user=cloudron
environment=HOME=/home/cloudron,USER=cloudron
directory=/app/code
command=/app/code/venv/bin/gunicorn {{ project_name }}.wsgi:application --bind unix:/run/{{ project_name }}/gunicorn.sock --workers 3 --timeout 120 --max-requests 1000 --max-requests-jitter 50 --forwarded-allow-ips="*" --access-logfile - --error-logfile -
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
