[program:celery-worker]
user=cloudron
environment=HOME=/tmp,USER=cloudron
directory=/app/code
command=/app/code/venv/bin/celery -A {{ project_name }} worker --loglevel=info --concurrency=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
