"""Celery application for blog, generated by dsd-cloudron.

The worker and beat supervisor programs run `celery -A blog`, which
imports this module. The broker and result backend come from CLOUDRON_REDIS_URL,
wired in cloudron_settings.py.
"""

import os

from celery import Celery

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "blog.settings")

app = Celery("blog")
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()
