"""Celery application for {{ cookiecutter.project_slug }}, generated by dsd-cloudron.

The worker and beat supervisor programs run `celery -A {{ cookiecutter.project_slug }}`, which
imports this module. The broker and result backend come from CLOUDRON_REDIS_URL,
wired in cloudron_settings.py.
"""

import os

from celery import Celery

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "{{ cookiecutter.project_slug }}.settings")

app = Celery("{{ cookiecutter.project_slug }}")
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()
