"""Settings for {{ cookiecutter.project_slug }}.

Local-development defaults live here. On Cloudron the cloudron_settings module
(generated by dsd-cloudron) overrides them; it is gated on CLOUDRON_APP_ORIGIN so
it stays inert during local development.
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = Path("/app/data")  # writable + persistent on Cloudron

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-insecure-key-change-me")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
{% if cookiecutter.use_sso == "yes" %}    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "allauth.mfa",
{% endif %}{% if cookiecutter.use_htmx == "yes" %}    "django_htmx",
    "crispy_forms",
    "crispy_bootstrap5",
{% endif %}    "{{ cookiecutter.project_slug }}.accounts",
    "{{ cookiecutter.project_slug }}.core",
]
# Celery adds no INSTALLED_APPS entry: M0's celery-beat supervisor conf runs the
# default file-based scheduler (`beat --schedule /app/data/celerybeat-schedule`),
# not django_celery_beat's DatabaseScheduler, so installing django_celery_beat
# would ship an admin UI whose periodic tasks never fire. v1 schedules no jobs;
# if a DB-backed beat is wanted later, add the app AND switch M0's beat conf to
# `--scheduler django_celery_beat.schedulers:DatabaseScheduler` together.

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
{% if cookiecutter.use_htmx == "yes" %}    "django_htmx.middleware.HtmxMiddleware",
{% endif %}{% if cookiecutter.use_sso == "yes" %}    "allauth.account.middleware.AccountMiddleware",
{% endif %}]

ROOT_URLCONF = "{{ cookiecutter.project_slug }}.urls"
WSGI_APPLICATION = "{{ cookiecutter.project_slug }}.wsgi.application"
ASGI_APPLICATION = "{{ cookiecutter.project_slug }}.asgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
# Local development against the docker-compose harness: when POSTGRES_HOST is set
# (the compose web service sets it; a bare `runserver` does not), use the Postgres
# and Redis services instead of the sqlite / local-memory defaults. Both lookups
# are env-gated and import no extra package at settings-eval time (the CACHES backend
# is a lazy string Django never imports during check/migrate). The bake tests run
# their `manage.py` subprocesses with a scrubbed env (POSTGRES_HOST/REDIS_URL/AWS_*
# removed - see _clean_env), so these blocks stay inert there regardless of the
# runner's shell. On Cloudron this whole module is replaced by cloudron_settings.py
# (gated on CLOUDRON_APP_ORIGIN).
if os.environ.get("POSTGRES_HOST"):
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "{{ cookiecutter.project_slug }}"),
        "USER": os.environ.get("POSTGRES_USER", "{{ cookiecutter.project_slug }}"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ["POSTGRES_HOST"],
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
{% if cookiecutter.use_redis == "yes" %}if os.environ.get("REDIS_URL"):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ["REDIS_URL"],
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        }
    }
{% endif %}
AUTH_USER_MODEL = "accounts.User"
SITE_ID = 1
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

{% if cookiecutter.use_htmx == "yes" %}CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
{% endif %}{% if cookiecutter.use_sso == "yes" %}AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
LOGIN_REDIRECT_URL = "/"
# allauth.account + allauth.mfa ship installed at their defaults (username login).
# Email-first login and mandatory verification are a settings switch, left to the
# user because the exact keys depend on the installed allauth major:
# ACCOUNT_LOGIN_METHODS / ACCOUNT_EMAIL_VERIFICATION on allauth >=65,
# ACCOUNT_AUTHENTICATION_METHOD / ACCOUNT_EMAIL_REQUIRED on older releases. The
# template deliberately sets none so a clean `check` cannot couple to an allauth
# version bump (see the scope note in the Self-Review).
{% endif %}{% if cookiecutter.use_s3 == "yes" %}# S3-compatible object storage for media. Env-gated, so it is inert until the bucket
# name is a real environment variable at settings-eval time. Cloudron has no managed
# S3 addon, so activate it one of two ways: (1) set AWS_STORAGE_BUCKET_NAME (and the
# other AWS_* vars) in the Cloudron app's Environment configuration, which makes this
# block fire; or (2) assign the full STORAGES dict (plus AWS_* values) directly in
# /app/data/custom_settings.py, which cloudron_settings.py execs and which overrides
# this block via `from .cloudron_settings import *`. Putting ONLY AWS_STORAGE_BUCKET_NAME
# in custom_settings.py does NOT activate S3: this block has already evaluated (and
# skipped) by the time custom_settings.py runs. The env-var path also drives the
# local docker-compose dev setup.
if os.environ.get("AWS_STORAGE_BUCKET_NAME"):
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    AWS_STORAGE_BUCKET_NAME = os.environ["AWS_STORAGE_BUCKET_NAME"]
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "")
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "")
{% endif %}

# Cloudron overrides (generated by dsd-cloudron; inert unless CLOUDRON_APP_ORIGIN).
# Only swallow the file's ABSENCE (local dev, bake tests). An ImportError raised
# *inside* cloudron_settings.py - a typo, a missing dependency - must propagate;
# otherwise the app silently falls back to these insecure dev defaults (DEBUG=True,
# the throwaway SECRET_KEY) in production, which fails open.
try:
    from .cloudron_settings import *  # noqa: F401,F403
except ImportError as exc:
    if not (exc.name and exc.name.endswith("cloudron_settings")):
        raise
