FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /app/code
RUN apt-get update \
    && apt-get install -y --no-install-recommends libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir uv
COPY pyproject.toml /app/code/pyproject.toml
RUN uv pip install --system -r pyproject.toml
COPY . /app/code/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
